version: '{build}'

image:
  - Visual Studio 2017

platform:
  - x64

configuration:
  - Release

environment:
  CMAKE_ARGS: -DTARGET_ISA=AVX2

shallow_clone: true

build:
  parallel: true

matrix:
  fast_finish: true

build_script:
  - ctest -V -C %Configuration% -S cmake/TestVecCore.cmake

notifications:
  - provider: Email
    to: amadio@cern.ch
    on_build_failure: true
    on_build_success: false
    on_build_status_changed: true
